apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
  namespace: demo
data:
  SPRING_DATASOURCE_URL: jdbc:mysql.demo.svc.cluster.local:3306/demo
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: gus45678!