apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo # 모든 리소스에 demo 네임스페이스 적용

# demo 네임 스페이스에 포함시킬 목록 
resources:
  - gitops-namespace.yaml
  - gitops-configmap.yaml
  - gitops-mysql-deployment.yaml
  - gitops-mysql-service.yaml
  - gitops-deployment.yaml
  - gitops-service.yaml

images:
  - name: docker.io/soohyun97/demo
    newName: docker.io/soohyun97/demo
    newTag: 0d6df1a